# Generated by Django 4.1.3 on 2022-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
