# Generated by Django 4.1.3 on 2022-11-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_rename_create_date_news_modate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news", old_name="modate", new_name="create_date",
        ),
    ]
