# Generated by Django 4.1.3 on 2022-11-17 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_rename_modate_news_create_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="create_date",),
        migrations.AddField(
            model_name="news",
            name="modate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
