# Generated by Django 4.1.3 on 2022-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="member", table="usermember",),
    ]
