# Generated by Django 4.1.3 on 2022-11-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_alter_member_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="member", table="member",),
    ]
